config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/quit' => 'customers#quit'
    patch 'customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update,]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :create, :destroy]
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders ,only: [:new, :index, :show,:create]
  end
  namespace :admin do
    get '/' => 'homes#top'
    resources :items
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index,:show,:edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  devise_for :customers,skip: [:passwords], controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

   devise_for :admin, sikp: [:registrations, :passwords] ,controllers:{
    sessions: 'admin/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         has_many :cart_items, dependent: :destroy
      
         has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image


  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  def add_tax_sales_price
    (self.price * 1.10).round
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
   has_many :cart_items, dependent: :destroy
   has_many :order_details, dependent: :destroy


  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  def add_tax_sales_price
    (self.price * 1.10).round
  end
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
   has_many :order_details
    belongs_to :customer
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end


  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :telephone_number, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  def update

    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to  admin_order_path(order.id)

  end
  private
  def customer_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>

<h4>商品名</h4>
<%= f.text_field :name %>


<%= f.submit '新規登録', class: 'btn btn-success' %>

<% end %>

app/views/admin/genres/index.html.erb
    
      

            <%= form_with model: @genre, url: admin_genres_path do |f| %>
            <h4>ジャンル一覧.追加</h4>
            ジャンル名　<%= f.text_field :name %>
            
            <%= f.submit '新規登録', class: 'btn btn-success' %>
            <% end %>
            <h4>ジャンル</h4>
            <% @genres.each do |genre| %>
            <%= genre.name %>
            <%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %></br>
            <% end %>
  

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="admin-heading col-3">
      <h2 class="mb-4 pt-3 pb-3 text-center">注文履歴一覧</h2>
    </div>
    <div class="col-8 mx-auto">
      <table class="table table-hover rounded-top rounded-bottom table_border_radius admin-order-table">
        <thead class="thead-dark">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= link_to "#{order.created_at.strftime('%Y/%m/%d %H:%M:%S')}", admin_order_path(order.id), class: "text-dark border-bottom border-dark" %></td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
<h4>画像</h4>
<%= f.file_field :image, accept: "image/*" %>
<h4>商品名</h4>
<%= f.text_field :name %>
<h4>商品説明</h4>
<%= f.text_area :introduction %>
<h4>税抜き価格</h4>
<%= f.text_field :price %> 円
<h4>販売ステータス</h4>
  <label><%= f.radio_button :is_active, true %>販売中</label>
	<label><%= f.radio_button :is_active, false %>販売停止</label></br>
<%= f.submit '変更を保存', class: 'btn btn-success' %>

<% end %>

app/views/admin/items/index.html.erb
<script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>



<div class="guide-plate d-flex align-items-center justify-content-center">
  <div class=admin-page-title>商品一覧</div>
  <div class= "content-end">
       <%= link_to new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-3x new-button"></i>
        <% end %>
        </div>
</div>


<div class="admin-products-cover1 d-flex align-items-center justify-content-center">
  <div class="admin-products-cover2 d-flex align-items-center justify-content-center">
    <div class="overflow-auto" style="width:100%; height:500px">
      <div class="container">
        <div class="row">
          <table class='table table-borderless table-hover'>
            <thead>
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%=link_to  item.name, admin_item_path(item.id)%></td>
                  <td><%= item.price %></td>
                  <td></td>
                  <td>
                  <% if item.is_active  %>
                    <p class="text-success">販売中</p></br>
                    <% else %>
                    <p class="text-secondary">販売停止中</p></br>
                    <% end %>
                  </td>
                </tr>
                 <%= paginate @items %>
              <% end %>
             
            </tbody>
          </table>
　　　  </div>
　　　</div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5"></div>
    <div class="col-lg-7">
      <div class="box3 d-flex align-items-center justify-content-center">
        <div class="overflow-auto" style="width:70%; height:70%">
          <%= form_with model: @item, url: admin_items_path do |f| %>
            <h4>商品画像</h4>
            <%= f.file_field :image, accept: "image/*" %>
            <h4>商品名</h4>
            <%= f.text_field :name %>
            <h4>商品説明</h4>
            <%= f.text_area :introduction %>
            <h4>ジャンル</h4>

            <h4>税抜価格</h4>
            <%= f.text_field :price %>
            <h4>販売ステータス</h4>
            <label><%= f.radio_button :is_active, true %>販売中</label>
            <label><%= f.radio_button :is_active, false %>販売停止</label></br>
            <%= f.submit '新規登録', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
       <div class="guide-plate d-flex align-items-center justify-content-center">
  <div class=admin-page-title>商品詳細</div>
</div>

<div class="admin-products-cover1 d-flex align-items-center justify-content-center">
  <div class="admin-products-cover2 d-flex align-items-center justify-content-center">
    <div class="overflow-auto" style="width:100%; height:500px">
      <div class="container">
        <div class="row">
          <div class="col-lg-1"></div>
          <div class="col-lg-3">
            <% if @item.image.attached? %>
            <%=image_tag @item.image, size: "200x200" %>
            <% else %>
             <%= image_tag 'no_image', size: "200x200" %>
             <% end %>
          </div>
          <div class="col-lg-1"></div>
          <div class="col-lg-7">
            <table class='table table-borderless'>
              <tr>
            	  <th>商品名</th>
            	  <td><%= @item.name %></td>
              </tr>
              <tr>
            	  <th>商品説明</th>
            	  <th><%= @item.introduction %></th>
              </tr>
              <tr>
            	  <th>ジャンル</th>
            	  <td></td>
              </tr>
              <tr>
            	  <th>税込価格</br>
                   (税抜価格）</th>
            	  <th>
            	    <%= @item.add_tax_sales_price.to_s(:dalimited) %>(<%= @item.price %>)円
            	  </th>
              </tr>
              <tr>
            	  <th>販売ステータス</th>
            	  <th>
                    <% if @item.is_active  %>
                    <span class="text-success">販売中</span></br>
                    <% else %>
                    <span class="text-secondary">販売停止中</span></br>
                    <% end %>
                </th>
              </tr>
              <tr>
                <th><%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success" %></th>
              </tr>
            </table>
          </div>
　　　  </div>
　　　</div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="admin-heading col-md-12">
      <h3 class="mb-4 col-3 pt-2 pb-2">注文履歴詳細</h3>
    </div>
    <table class="table table-sm mb-3 admin-order-show-table">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to "#{@order.name}", "", class: "text-dark border-bottom border-dark" %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"]], class: "form-control" %>
            <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row mb-5">
    <div class="col-7">
      <table class="table mt-3 table-borderless table-hover rounded-top rounded-bottom table_border_radius admin-order-table">
        <thead class="thead-dark">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td>
              <% @products_price = order_detail.price * order_detail.amount %>
              <%= @products_price %>
            </td>
            <td>
            <%= form_with model: order_detail, url: admin_order_detail_path do |f| %>
              <%= f.select :status, [["着手不可", "着手不可"], ["製作待ち", "製作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"]], class: "form-control" %>
              <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
            <% end %>
          </td>
            <% @sum += @products_price %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @sum %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td>800円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @sum + 800 %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
 