config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/quit' => 'customers#quit'
    patch 'customers/out' => 'customers#out'
    resources :customers, only: [:show, :edit, :update,]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :update, :create, :destroy]
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders ,only: [:new, :index, :show,:create]
  end
  namespace :admin do
    get '/' => 'homes#top'
    resources :items
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index,:show,:edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  devise_for :customers,skip: [:passwords], controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

   devise_for :admin, sikp: [:registrations, :passwords] ,controllers:{
    sessions: 'admin/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         has_many :cart_items, dependent: :destroy
      
         has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image


  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  def add_tax_sales_price
    (self.price * 1.10).round
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
   has_many :cart_items, dependent: :destroy
   has_many :order_details, dependent: :destroy


  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  def add_tax_sales_price
    (self.price * 1.10).round
  end
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
   has_many :order_details
    belongs_to :customer
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end


  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :telephone_number, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>
       <li class: "navbar-text text-dark ">
      ようこそ、<%= current_customer.last_name %>さん！
       </li>

      <li>
        <%= link_to "マイページ",  public_customer_path(current_customer.id), class: "nav-link text-dark" %>
      </li>
      <li>
        <%= link_to "商品一覧", public_items_path, class: "nav-link text-dark" %>
      </li>
      <li>
        <%= link_to "カート",  public_cart_items_path, class: "nav-link text-dark" %>
      </li>
      <li>
        <%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: "nav-link text-dark" %>
      </li>


      <% elsif admin_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark" %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-dark"%>
      </li>
      <li>
        <%= link_to "注文一覧", admin_path, class: "nav-link text-dark" %>
      </li>
       <li>
        <%= link_to "ジャンル一覧", admin_genres_path,  class: "nav-link text-dark"%>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %>
      </li>
      <% else %>
      <li>
        <%= link_to "About",  public_about_path, class: "nav-link text-dark"%>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-dark"%>
      </li>
      <li>
        <%= link_to "ログイン", customer_session_path, class: "nav-link text-dark"%>
      </li>

      <% end %>
      </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
  <footer>
      <div class="mt-3"></div>
    </footer>
</html>